// @ts-nocheck
import React, { useMemo, useState } from 'react';
import { BookOpen, Check, ChevronRight, Code2, Copy, Download, ExternalLink, KeyRound, Loader2, Plug, Plus, Save, Search, Sparkles, X } from 'lucide-react';
import { ApiConnectionItem, ApiConnectionsDocument, ApiCostModel } from '../types';
import VoiceDictationButton from './VoiceDictationButton';
import { ensureTursoSession } from '../lib/turso';

interface Props { document: ApiConnectionsDocument; title?: string; canEdit?: boolean; onSave:(document:ApiConnectionsDocument)=>void; onClose:()=>void; }
interface CatalogEntry {
  id:string; name:string; category:string; summary:string; costModel:ApiCostModel; auth:string; docsUrl:string;
  envVars:string[]; capabilities:string[]; setup:string[]; compatibility?:string; caution?:string;
}
const uid=(p='api')=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;
export const blankApiConnections=():ApiConnectionsDocument=>({title:'APIs & Conexões',connections:[],builderPrompt:''});

const CATALOG:CatalogEntry[]=[
{id:'google-fonts',name:'Google Fonts Developer API',category:'Tipografia',summary:'Consulta famílias, variantes, scripts e metadados do Google Fonts.',costModel:'free-tier',auth:'API key',docsUrl:'https://developers.google.com/fonts/docs/developer_api',envVars:['GOOGLE_FONTS_API_KEY'],capabilities:['listar fontes','buscar famílias','variantes e eixos'],setup:['Crie/seleciona um projeto no Google Cloud.','Ative Web Fonts Developer API.','Crie uma API key.','Adicione GOOGLE_FONTS_API_KEY nas variáveis da Vercel.']},
{id:'gemini',name:'Gemini Developer API',category:'IA generativa',summary:'Texto, imagem, áudio e raciocínio multimodal pelo Gemini. Use apenas o nível gratuito do Google AI Studio para manter custo zero.',costModel:'free-tier',auth:'API key gratuita do Google AI Studio; não habilite faturamento',docsUrl:'https://ai.google.dev/gemini-api/docs',envVars:['GEMINI_API_KEY'],capabilities:['texto e multimodal','visão','JSON estruturado','ideação','análise de imagem','assistentes criativos'],setup:['Crie uma chave em um projeto do Google AI Studio sem faturamento.','Adicione GEMINI_API_KEY nas variáveis da Vercel.','Escolha somente modelos que exibem Free Tier na documentação atual.'],caution:'Para custo zero garantido pelo projeto, mantenha o faturamento desativado. Ao atingir a cota gratuita, trate 429/limite e pare a chamada; não faça fallback automático para tier pago.'},
{id:'transformers-js',name:'Transformers.js',category:'IA local / WebGPU',summary:'Modelos de IA executados no próprio navegador via WASM/WebGPU: embeddings, classificação, visão, áudio e linguagem sem pagar uma API remota.',costModel:'open-self-hosted',auth:'Sem chave; modelos são baixados pelo navegador',docsUrl:'https://huggingface.co/docs/transformers.js/',envVars:[],capabilities:['IA local','WebGPU','embeddings','classificação','visão','Whisper/áudio'],setup:['Instale @huggingface/transformers.','Prefira modelos quantizados e pequenos para web.','Use WASM como fallback quando WebGPU não estiver disponível.'],compatibility:'WebGPU varia por navegador/dispositivo; WASM amplia compatibilidade.'},
{id:'tensorflow-js',name:'TensorFlow.js',category:'IA local / WebGPU',summary:'Machine learning em JavaScript no navegador ou Node, com modelos prontos, treinamento e transfer learning sem cobrança de API.',costModel:'open-self-hosted',auth:'Sem chave',docsUrl:'https://www.tensorflow.org/js',envVars:[],capabilities:['ML no navegador','modelos pré-treinados','transfer learning','visão','gestos'],setup:['Instale @tensorflow/tfjs.','Escolha backend WebGL/WebGPU/WASM conforme o caso.','Otimize modelos para dispositivos móveis.']},
{id:'mediapipe',name:'MediaPipe Tasks',category:'IA local / visão',summary:'Visão computacional local para face, pose, mãos, segmentação e detecção em imagem, vídeo e câmera.',costModel:'open-self-hosted',auth:'Sem chave para execução local',docsUrl:'https://ai.google.dev/edge/mediapipe/solutions/guide',envVars:[],capabilities:['pose','face landmarks','mãos','segmentação','detecção de objetos','imagem ao vivo'],setup:['Use o pacote MediaPipe Tasks para Web.','Carregue o modelo apropriado.','Execute localmente e trate permissões de câmera quando necessário.']},
{id:'opencv-js',name:'OpenCV.js',category:'Imagem / visão',summary:'Processamento de imagem e visão computacional no navegador: filtros, recortes, contornos, perspectiva, tracking e análise visual.',costModel:'open-self-hosted',auth:'Sem chave',docsUrl:'https://docs.opencv.org/5.x/d5/d10/tutorial_js_root.html',envVars:[],capabilities:['filtros','contornos','threshold','perspectiva','tracking','processamento de imagem'],setup:['Carregue OpenCV.js localmente ou pelo build oficial.','Converta imagem/canvas para cv.Mat.','Libere Mats após o uso para evitar vazamento de memória.']},
{id:'iconify',name:'Iconify Public API',category:'Design / ícones',summary:'Mais de 300 mil ícones de centenas de conjuntos open source, consultáveis e renderizáveis como SVG.',costModel:'no-key',auth:'Sem chave na API pública',docsUrl:'https://iconify.design/docs/api/',envVars:[],capabilities:['buscar ícones','SVG','coleções','ícones por nome'],setup:['Consulte a API pública ou use o pacote local.','Verifique a licença do conjunto de ícones escolhido antes de publicar.'],caution:'A API pública é gratuita, mas as licenças variam entre os conjuntos de ícones.'},
{id:'thecolorapi',name:'The Color API',category:'Cor / design system',summary:'Converte cores, identifica nomes e gera esquemas monocromáticos, análogos, complementares, tríades e quádruplas.',costModel:'no-key',auth:'Sem chave',docsUrl:'https://www.thecolorapi.com/docs',envVars:[],capabilities:['nomear cores','HEX/RGB/HSL/CMYK','contraste','paletas','harmonias cromáticas'],setup:['Use /id para identificar/converter cores.','Use /scheme para gerar paletas a partir de uma cor-semente.']},
{id:'openverse',name:'Openverse API',category:'Imagem e mídia aberta',summary:'Busca imagens e áudio com licenças abertas para referência, colagem, moodboards e pesquisa visual.',costModel:'no-key',auth:'Consultas anônimas funcionam com limites; autenticação gratuita é opcional',docsUrl:'https://api.openverse.org/v1/',envVars:[],capabilities:['buscar imagens','buscar áudio','licenças abertas','moodboard','referências visuais'],setup:['Comece com requisições anônimas.','Leia a licença de cada resultado antes de reutilizar.','Se precisar de limites maiores, registre um cliente gratuito.'],caution:'Há rate limits e limites de paginação. A licença deve ser verificada em cada obra.'},
{id:'artic',name:'Art Institute of Chicago API',category:'Arte e cultura',summary:'Coleção pública do Art Institute of Chicago com obras, artistas, metadados e imagens via IIIF.',costModel:'no-key',auth:'Sem autenticação; limite público por IP',docsUrl:'https://api.artic.edu/docs/',envVars:[],capabilities:['obras de arte','artistas','imagens IIIF','busca','metadados curatoriais'],setup:['Acesse os endpoints REST sem chave.','Use IIIF para solicitar tamanhos de imagem.','Considere enviar AIC-User-Agent em aplicações públicas.']},
{id:'cleveland-open-access',name:'Cleveland Museum Open Access API',category:'Arte e cultura',summary:'Mais de 61 mil registros em domínio público/CC0 do Cleveland Museum of Art, com metadados e imagens abertas.',costModel:'no-key',auth:'Sem chave ou token para a API pública de Open Access',docsUrl:'https://www.clevelandart.org/open-access',envVars:[],capabilities:['obras CC0','imagens abertas','artistas','coleções','pesquisa visual'],setup:['Consulte apenas registros e imagens marcados como Open Access/CC0 quando quiser reutilização livre.']},
{id:'paperjs',name:'Paper.js',category:'Vetor / ilustração',summary:'Framework vetorial open source para paths, Bézier, operações geométricas e desenho procedural sobre Canvas.',costModel:'open-self-hosted',auth:'Sem chave',docsUrl:'https://paperjs.org/reference/',envVars:[],capabilities:['vetores','Bézier','paths','geometria','desenho procedural'],setup:['Instale Paper.js.','Crie um PaperScope/Project e associe a um canvas.']},
{id:'fabricjs',name:'Fabric.js',category:'Vetor / canvas',summary:'Canvas interativo orientado a objetos com seleção, transformação, serialização e exportação SVG.',costModel:'open-self-hosted',auth:'Sem chave',docsUrl:'https://fabricjs.com/docs/',envVars:[],capabilities:['canvas editável','seleção','camadas','SVG','JSON','transformações'],setup:['Instale Fabric.js.','Crie Canvas/StaticCanvas.','Serialize o estado em JSON e exporte SVG quando necessário.']},
{id:'roughjs',name:'Rough.js',category:'Vetor / ilustração',summary:'Gera linhas, formas e paths SVG/Canvas com aparência desenhada à mão, excelente para wireframes e ilustração expressiva.',costModel:'open-self-hosted',auth:'Sem chave',docsUrl:'https://roughjs.com/',envVars:[],capabilities:['sketch','hand-drawn','SVG','Canvas','wireframe expressivo'],setup:['Instale roughjs.','Use rough.svg ou rough.canvas conforme o editor.']},
{id:'tonejs',name:'Tone.js',category:'Áudio criativo',summary:'Framework Web Audio para sintetizadores, efeitos, sequenciamento e música interativa no navegador.',costModel:'open-self-hosted',auth:'Sem chave',docsUrl:'https://tonejs.github.io/',envVars:[],capabilities:['sintetizadores','efeitos','sequencer','áudio interativo','sonificação'],setup:['Instale tone.','Inicie o AudioContext após gesto do usuário.','Use Transport para sincronização musical.']},
{id:'hydra-synth',name:'Hydra Synth',category:'Creative coding',summary:'Sintetizador de vídeo live-coding em WebGL para feedback, distorções, câmera, áudio reativo e visuais generativos.',costModel:'open-self-hosted',auth:'Sem chave',docsUrl:'https://hydra.ojack.xyz/',envVars:[],capabilities:['video synth','feedback','WebGL','live coding','visuais generativos','áudio reativo'],setup:['Use hydra-synth como módulo ou a versão web.','Combine com câmera, p5.js, Three.js ou Tone.js.'],compatibility:'Funciona melhor em navegadores com WebGL robusto.'},
{id:'d3js',name:'D3.js',category:'Visualização de dados',summary:'Biblioteca livre para visualizações de dados altamente autorais com SVG, Canvas, mapas, redes, força e animação.',costModel:'open-self-hosted',auth:'Sem chave',docsUrl:'https://d3js.org/',envVars:[],capabilities:['dataviz','SVG','mapas','redes','force layout','animação','formas'],setup:['Instale d3.','Combine módulos de escalas, shapes, layouts e interações conforme o projeto.']},
{id:'maplibre',name:'MapLibre GL JS',category:'Mapas',summary:'Mapas vetoriais interativos WebGL sem dependência de fornecedor proprietário.',costModel:'open-self-hosted',auth:'Sem chave para a biblioteca; tiles dependem do provedor',docsUrl:'https://maplibre.org/maplibre-gl-js/docs/',envVars:[],capabilities:['mapas','markers','layers','GeoJSON','globo 3D'],setup:['Instale/carregue MapLibre.','Escolha uma fonte de tiles compatível.','Respeite a licença/política do provedor de tiles.']},
{id:'osm',name:'OpenStreetMap',category:'Mapas',summary:'Dados cartográficos abertos. Use um provedor de tiles adequado para produção.',costModel:'no-key',auth:'Sem chave para dados; políticas de tiles se aplicam',docsUrl:'https://wiki.openstreetmap.org/wiki/API',envVars:[],capabilities:['dados geográficos','ruas','POIs'],setup:['Consulte a política do endpoint/tiles que usar.','Atribua OpenStreetMap contributors.']},
{id:'nominatim',name:'Nominatim',category:'Mapas',summary:'Geocodificação e busca de lugares sobre dados OpenStreetMap.',costModel:'no-key',auth:'Sem chave na instância pública; uso limitado',docsUrl:'https://nominatim.org/release-docs/latest/api/Overview/',envVars:[],capabilities:['geocodificar endereço','reverse geocoding','buscar lugar'],setup:['Use User-Agent identificável.','Evite alto volume na instância pública.'],caution:'A instância pública tem política de uso/rate limit; para volume alto, hospede ou use um provedor.'},
{id:'overpass',name:'Overpass API',category:'Mapas',summary:'Consultas flexíveis aos dados do OpenStreetMap.',costModel:'no-key',auth:'Sem chave',docsUrl:'https://wiki.openstreetmap.org/wiki/Overpass_API',envVars:[],capabilities:['consultar POIs','filtros geográficos','dados OSM'],setup:['Escolha uma instância pública.','Evite consultas pesadas/repetitivas.']},
{id:'crossref',name:'Crossref REST API',category:'Pesquisa',summary:'Metadados de DOI, artigos, autores, periódicos e referências.',costModel:'no-key',auth:'Público sem autenticação; modo polite usa e-mail',docsUrl:'https://www.crossref.org/documentation/retrieve-metadata/rest-api/',envVars:[],capabilities:['buscar DOI','metadados acadêmicos','citações'],setup:['Prefira enviar mailto ou User-Agent com contato.']},
{id:'openalex',name:'OpenAlex API',category:'Pesquisa',summary:'Grafo aberto de produção científica: works, authors, sources, institutions e topics.',costModel:'free-tier',auth:'Chave gratuita para uso regular conforme política atual',docsUrl:'https://docs.openalex.org/',envVars:['OPENALEX_API_KEY'],capabilities:['buscar trabalhos','autores','instituições','tópicos'],setup:['Crie uma chave conforme documentação do OpenAlex.','Adicione OPENALEX_API_KEY na Vercel.']},
{id:'wikimedia',name:'MediaWiki / Wikimedia APIs',category:'Pesquisa e mídia',summary:'Busca, páginas, imagens e metadados da Wikipédia/Wikimedia.',costModel:'no-key',auth:'Sem chave para grande parte das APIs públicas',docsUrl:'https://www.mediawiki.org/wiki/API:Main_page',envVars:[],capabilities:['buscar verbetes','imagens Wikimedia','conteúdo estruturado'],setup:['Identifique seu app quando solicitado.','Respeite licenças de cada mídia.']},
{id:'wikidata',name:'Wikidata Query Service',category:'Pesquisa',summary:'Consultas SPARQL sobre dados estruturados e relações entre entidades.',costModel:'no-key',auth:'Sem chave',docsUrl:'https://www.wikidata.org/wiki/Wikidata:SPARQL_query_service',envVars:[],capabilities:['SPARQL','entidades','relações','dados multilíngues'],setup:['Construa consultas SPARQL eficientes.','Evite consultas excessivamente pesadas.']},
{id:'gbif',name:'GBIF API',category:'Biodiversidade',summary:'Ocorrências de espécies, taxonomia e datasets globais de biodiversidade.',costModel:'no-key',auth:'Sem chave para leitura pública',docsUrl:'https://techdocs.gbif.org/en/openapi/',envVars:[],capabilities:['espécies','ocorrências','taxonomia','mapas de biodiversidade'],setup:['Use endpoints públicos de leitura.']},
{id:'nasa',name:'NASA Open APIs',category:'Ciência',summary:'APIs públicas para astronomia, imagens e dados da NASA.',costModel:'free-tier',auth:'API key gratuita; DEMO_KEY para experimentação limitada',docsUrl:'https://api.nasa.gov/',envVars:['NASA_API_KEY'],capabilities:['APOD','Mars Rover','asteroides','imagens'],setup:['Solicite uma chave gratuita.','Adicione NASA_API_KEY na Vercel.']},
{id:'openmeteo',name:'Open-Meteo',category:'Clima',summary:'Previsão e dados meteorológicos sem chave para usos compatíveis com a política gratuita.',costModel:'no-key',auth:'Sem chave no uso público gratuito',docsUrl:'https://open-meteo.com/en/docs',envVars:[],capabilities:['previsão','histórico','geocoding climático'],setup:['Escolha latitude/longitude.','Verifique limites e atribuição.']},
{id:'metmuseum',name:'The Met Collection API',category:'Arte e cultura',summary:'Coleção aberta do Metropolitan Museum of Art.',costModel:'no-key',auth:'Sem chave',docsUrl:'https://metmuseum.github.io/',envVars:[],capabilities:['obras','artistas','imagens open access'],setup:['Filtre isPublicDomain quando precisar reutilizar imagens.']},
{id:'europeana',name:'Europeana APIs',category:'Arte e cultura',summary:'Patrimônio cultural europeu: objetos, imagens, coleções e metadados.',costModel:'free-tier',auth:'API key gratuita mediante cadastro',docsUrl:'https://pro.europeana.eu/page/apis',envVars:['EUROPEANA_API_KEY'],capabilities:['coleções','objetos culturais','imagens','busca'],setup:['Solicite uma API key gratuita.','Adicione EUROPEANA_API_KEY na Vercel.']},
{id:'brasilapi',name:'BrasilAPI',category:'Brasil',summary:'CEP, bancos, feriados, DDD, CNPJ e outros dados públicos agregados.',costModel:'no-key',auth:'Sem chave',docsUrl:'https://brasilapi.com.br/docs',envVars:[],capabilities:['CEP','feriados','DDD','bancos','dados brasileiros'],setup:['Use somente os endpoints necessários e trate indisponibilidade das fontes agregadas.']},
{id:'ibge',name:'APIs IBGE',category:'Brasil',summary:'Localidades, agregados, nomes e estatísticas do IBGE.',costModel:'no-key',auth:'Sem chave',docsUrl:'https://servicodados.ibge.gov.br/api/docs/',envVars:[],capabilities:['municípios','estados','estatísticas','nomes'],setup:['Escolha a API temática adequada no portal do IBGE.']},
{id:'webxr',name:'WebXR Device API',category:'RA / VR',summary:'Sessões imersivas de realidade virtual e aumentada no navegador.',costModel:'no-key',auth:'API do navegador; requer HTTPS e suporte do dispositivo',docsUrl:'https://developer.mozilla.org/en-US/docs/Web/API/WebXR_Device_API',envVars:[],capabilities:['VR','AR','tracking','controllers','hit test'],setup:['Sirva via HTTPS.','Teste suporte com navigator.xr.','Planeje fallback para navegadores sem WebXR.'],compatibility:'Disponibilidade limitada entre navegadores/dispositivos.'},
{id:'aframe',name:'A-Frame',category:'RA / VR',summary:'Framework web open source para cenas WebXR/3D declarativas.',costModel:'open-self-hosted',auth:'Sem chave',docsUrl:'https://aframe.io/docs/',envVars:[],capabilities:['VR','WebXR','cenas 3D','componentes'],setup:['Carregue A-Frame.','Combine com assets 3D e WebXR.']},
{id:'arjs',name:'AR.js',category:'RA / VR',summary:'AR open source no navegador, incluindo marker/location-based AR.',costModel:'open-self-hosted',auth:'Sem chave',docsUrl:'https://ar-js-org.github.io/AR.js-Docs/',envVars:[],capabilities:['AR por marcador','location based AR'],setup:['Use HTTPS e câmera.','Defina marcador ou localização.']},
{id:'mindar',name:'MindAR',category:'RA / VR',summary:'AR web open source com image tracking e face tracking.',costModel:'open-self-hosted',auth:'Sem chave',docsUrl:'https://hiukim.github.io/mind-ar-js-doc/',envVars:[],capabilities:['image tracking','face tracking','AR web'],setup:['Compile/alimente o target de imagem quando necessário.','Use HTTPS/câmera.']},
{id:'deviceorientation',name:'Device Orientation / Motion',category:'Sensores',summary:'Giroscópio/orientação e movimento do dispositivo quando permitido.',costModel:'no-key',auth:'Permissão do navegador/dispositivo',docsUrl:'https://developer.mozilla.org/en-US/docs/Web/API/Device_orientation_events',envVars:[],capabilities:['alpha beta gamma','aceleração','gestos físicos'],setup:['Solicite permissão quando o sistema exigir.','Ofereça alternativa sem movimento.']},
{id:'geolocation',name:'Geolocation API',category:'Sensores',summary:'Localização do dispositivo com consentimento.',costModel:'no-key',auth:'Permissão do usuário; HTTPS',docsUrl:'https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API',envVars:[],capabilities:['latitude','longitude','watch position'],setup:['Explique por que precisa da localização.','Trate recusa de permissão.']},
{id:'webserial',name:'Web Serial API',category:'Hardware',summary:'Ler/escrever dispositivos seriais, útil para Arduino/ESP via serial.',costModel:'no-key',auth:'Permissão explícita do usuário; HTTPS; suporte limitado',docsUrl:'https://developer.mozilla.org/en-US/docs/Web/API/Web_Serial_API',envVars:[],capabilities:['Arduino','ESP','sensores seriais','atuadores'],setup:['Use navegador compatível.','Chame requestPort a partir de gesto do usuário.','Defina baud rate correto.'],compatibility:'Disponibilidade limitada; Chrome/Edge costumam ter melhor suporte.'},
{id:'webbluetooth',name:'Web Bluetooth API',category:'Hardware',summary:'Conexão com periféricos Bluetooth Low Energy.',costModel:'no-key',auth:'Permissão explícita; HTTPS',docsUrl:'https://developer.mozilla.org/en-US/docs/Web/API/Web_Bluetooth_API',envVars:[],capabilities:['BLE','GATT','sensores sem fio'],setup:['Conheça services/characteristics do dispositivo.','Solicite requestDevice por gesto do usuário.'],compatibility:'Experimental/limitado entre navegadores.'},
{id:'webusb',name:'WebUSB API',category:'Hardware',summary:'Acesso a dispositivos USB compatíveis diretamente pelo navegador.',costModel:'no-key',auth:'Permissão do usuário; HTTPS',docsUrl:'https://developer.mozilla.org/en-US/docs/Web/API/USB',envVars:[],capabilities:['USB customizado','microcontroladores'],setup:['Confirme compatibilidade do dispositivo e navegador.']},
{id:'webhid',name:'WebHID API',category:'Hardware',summary:'Acesso a dispositivos HID além do conjunto padrão do navegador.',costModel:'no-key',auth:'Permissão do usuário; HTTPS',docsUrl:'https://developer.mozilla.org/en-US/docs/Web/API/WebHID_API',envVars:[],capabilities:['controles','sensores HID','dispositivos custom'],setup:['Solicite dispositivo a partir de ação do usuário.']},
{id:'gamepad',name:'Gamepad API',category:'Game',summary:'Leitura de controles/gamepads conectados ao navegador.',costModel:'no-key',auth:'API do navegador',docsUrl:'https://developer.mozilla.org/en-US/docs/Web/API/Gamepad_API',envVars:[],capabilities:['botões','analógicos','controles'],setup:['Escute gamepadconnected.','Mapeie controles e ofereça teclado/touch como fallback.']},
{id:'webaudio',name:'Web Audio API',category:'Áudio',summary:'Síntese, mixagem, filtros e análise de áudio no navegador.',costModel:'no-key',auth:'API do navegador',docsUrl:'https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API',envVars:[],capabilities:['sintetizar som','analyser','efeitos','mixagem'],setup:['Crie AudioContext após interação do usuário quando necessário.']},
{id:'mediarecorder',name:'MediaRecorder API',category:'Mídia',summary:'Grava streams de áudio/vídeo do navegador.',costModel:'no-key',auth:'API do navegador; permissões para câmera/mic',docsUrl:'https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder',envVars:[],capabilities:['gravar câmera','microfone','canvas capture'],setup:['Solicite MediaDevices quando houver câmera/microfone.','Cheque mimeType suportado.']},
{id:'webspeech',name:'Web Speech API',category:'Acessibilidade e voz',summary:'Reconhecimento e síntese de fala conforme suporte do navegador.',costModel:'no-key',auth:'API do navegador; implementação varia',docsUrl:'https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API',envVars:[],capabilities:['ditado','speech recognition','text-to-speech'],setup:['Cheque SpeechRecognition/webkitSpeechRecognition.','Ofereça digitação como fallback.']},
{id:'speechsynthesis',name:'SpeechSynthesis',category:'Acessibilidade e voz',summary:'Texto para fala com vozes disponibilizadas pelo sistema/navegador.',costModel:'no-key',auth:'API do navegador',docsUrl:'https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesis',envVars:[],capabilities:['TTS','vozes do sistema','idiomas'],setup:['Liste vozes disponíveis.','Não dependa só de áudio para informação essencial.']},
{id:'mediadevices',name:'MediaDevices',category:'Mídia',summary:'Acesso consentido à câmera e microfone.',costModel:'no-key',auth:'Permissão do usuário; HTTPS',docsUrl:'https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices',envVars:[],capabilities:['câmera','microfone','screen capture'],setup:['Solicite apenas quando necessário.','Mostre estado de gravação e privacidade.']},
{id:'webmidi',name:'Web MIDI API',category:'Hardware / som',summary:'Comunicação MIDI com instrumentos e controladores.',costModel:'no-key',auth:'Permissão/suporte do navegador',docsUrl:'https://developer.mozilla.org/en-US/docs/Web/API/Web_MIDI_API',envVars:[],capabilities:['MIDI input','MIDI output','controladores musicais'],setup:['Cheque navigator.requestMIDIAccess.']},
{id:'threejs',name:'Three.js',category:'3D',summary:'Biblioteca open source para renderização 3D/WebGL e integração com WebXR.',costModel:'open-self-hosted',auth:'Sem chave',docsUrl:'https://threejs.org/docs/',envVars:[],capabilities:['3D','WebGL','GLTF','WebXR'],setup:['Instale ou carregue Three.js.','Otimize assets e render loop.']},
{id:'p5js',name:'p5.js',category:'Creative coding',summary:'Creative coding 2D/WebGL para sketches, interação e audiovisual.',costModel:'open-self-hosted',auth:'Sem chave',docsUrl:'https://p5js.org/reference/',envVars:[],capabilities:['canvas','interação','generative art','som'],setup:['Carregue p5.js.','Crie setup/draw ou modo instance.']},
{id:'matterjs',name:'Matter.js',category:'Game / física',summary:'Motor de física 2D JavaScript para colisões, corpos e constraints.',costModel:'open-self-hosted',auth:'Sem chave',docsUrl:'https://brm.io/matter-js/docs/',envVars:[],capabilities:['física 2D','colisão','gravidade'],setup:['Carregue Matter.js.','Crie engine/world e corpos.']}
];

function badge(model:ApiCostModel){return model==='no-key'?'GRÁTIS · SEM CHAVE':model==='free-tier'?'GRÁTIS · COTA':'GRÁTIS · OPEN / LOCAL'}
function asConnection(entry:CatalogEntry):ApiConnectionItem{return{id:uid(),catalogId:entry.id,name:entry.name,category:entry.category,summary:entry.summary,costModel:entry.costModel,auth:entry.auth,docsUrl:entry.docsUrl,envVars:entry.envVars,capabilities:entry.capabilities,status:entry.envVars.length?'needs-config':'configured',notes:''}}

export function ApiConnectionsPreview({document,className=''}:{document:ApiConnectionsDocument;className?:string}){return <div className={`bg-white p-4 overflow-hidden ${className}`}><div className="text-[9px] font-mono text-neutral-500">APIs & CONEXÕES</div><b className="block text-lg mt-1">{document.connections.length} integrações</b><div className="mt-3 flex flex-wrap gap-1">{document.connections.slice(0,8).map(c=><span key={c.id} className="rounded-full bg-neutral-100 px-2 py-1 text-[8px]">{c.name}</span>)}</div></div>}

export default function ApiConnectionsStudio({document,title='APIs & Conexões',canEdit=true,onSave,onClose}:Props){
 const [draft,setDraft]=useState<ApiConnectionsDocument>({...blankApiConnections(),...JSON.parse(JSON.stringify(document)),connections:document.connections||[]});
 const [query,setQuery]=useState('');const [category,setCategory]=useState('Todas');const [selected,setSelected]=useState<CatalogEntry|null>(null);const [tab,setTab]=useState<'catalog'|'integrated'|'builder'>('catalog');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [builderResult,setBuilderResult]=useState<any>(null);
 const categories=useMemo(()=>['Todas',...Array.from(new Set(CATALOG.map(x=>x.category))).sort()],[]);
 const filtered=CATALOG.filter(x=>(category==='Todas'||x.category===category)&&`${x.name} ${x.summary} ${x.capabilities.join(' ')}`.toLowerCase().includes(query.toLowerCase()));
 const integratedIds=new Set(draft.connections.map(x=>x.catalogId).filter(Boolean));
 const integrate=(entry:CatalogEntry)=>{if(integratedIds.has(entry.id))return;setDraft(d=>({...d,connections:[...d.connections,asConnection(entry)]}))};
 const remove=(id:string)=>setDraft(d=>({...d,connections:d.connections.filter(x=>x.id!==id)}));
 const createApi=async()=>{if(!draft.builderPrompt?.trim())return setError('Descreva a API que você quer criar.');setBusy(true);setError('');try{const s=await ensureTursoSession().catch(()=>null);const r=await fetch('/api/mediators/think',{method:'POST',headers:{'Content-Type':'application/json',...(s?.token?{Authorization:`Bearer ${s.token}`}:{})},body:JSON.stringify({mode:'api-builder',freeOnly:true,prompt:`REGRA OBRIGATÓRIA: use apenas APIs sem cobrança, APIs com cota gratuita sem faturamento automático, recursos open source/self-hosted ou APIs nativas do navegador. Não proponha serviços pagos nem fallback pago. Se uma cota gratuita acabar, a integração deve falhar com mensagem clara, nunca gerar custo.\n\n${draft.builderPrompt}`,existingApis:draft.connections.map(c=>({name:c.name,capabilities:c.capabilities,envVars:c.envVars}))})});const data=await r.json().catch(()=>({}));if(!r.ok||!data.apiSpec)throw new Error(data.error||'A IA não conseguiu criar a especificação.');setBuilderResult(data.apiSpec)}catch(e:any){setError(e.message||'Falha ao criar API')}finally{setBusy(false)}};
 const addGenerated=()=>{if(!builderResult)return;const item:ApiConnectionItem={id:uid(),name:builderResult.name||'API criada no projeto',category:'API criada',summary:builderResult.summary||'',costModel:'open-self-hosted',auth:builderResult.auth||'Definido no código',docsUrl:'',envVars:Array.isArray(builderResult.envVars)?builderResult.envVars:[],capabilities:Array.isArray(builderResult.capabilities)?builderResult.capabilities:[],status:(builderResult.envVars||[]).length?'needs-config':'configured',customSpec:{endpoints:builderResult.endpoints||[],code:builderResult.code||'',fileName:builderResult.fileName||'api/custom.ts'}};setDraft(d=>({...d,connections:[...d.connections,item]}));setTab('integrated')};
 const downloadCode=(item:ApiConnectionItem)=>{const code=item.customSpec?.code;if(!code)return;const blob=new Blob([code],{type:'text/typescript'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=item.customSpec?.fileName?.split('/').pop()||'api.ts';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
 return <div className="fixed inset-0 z-[127] bg-[#EEEDE9] flex flex-col canvas-control atelier-studio" onPointerDown={e=>e.stopPropagation()}><header className="shrink-0 bg-white border-b px-3 sm:px-5 pt-[max(.35rem,env(safe-area-inset-top))] pb-2"><div className="flex items-center gap-3"><button onClick={onClose} className="h-11 w-11 rounded-xl flex items-center justify-center"><X size={20}/></button><div className="min-w-0 flex-1"><b className="block truncate">{title}</b><div className="text-[9px] font-mono text-neutral-500 uppercase">explorar · incorporar · configurar · criar API · PUBLICA</div></div><button disabled={!canEdit} onClick={()=>onSave({...draft,updatedAt:new Date().toISOString()})} className="h-11 px-4 rounded-xl bg-black text-white text-xs font-bold flex gap-2 items-center"><Save size={15}/> SALVAR</button></div><div className="mt-2 grid grid-cols-3 gap-1.5 sm:flex sm:gap-2"><button onClick={()=>setTab('catalog')} className={`h-10 min-w-0 px-1.5 sm:px-3 rounded-xl border text-[8px] sm:text-[9px] font-bold whitespace-nowrap ${tab==='catalog'?'bg-black text-white':''}`}>EXPLORAR</button><button onClick={()=>setTab('integrated')} className={`h-10 min-w-0 px-1.5 sm:px-3 rounded-xl border text-[8px] sm:text-[9px] font-bold whitespace-nowrap flex items-center justify-center gap-1 ${tab==='integrated'?'bg-black text-white':''}`}><span className="truncate">INTEGRADAS</span><span className={`shrink-0 min-w-5 h-5 px-1 rounded-full flex items-center justify-center text-[8px] ${tab==='integrated'?'bg-white/20 text-white':'bg-neutral-100 text-neutral-700'}`}>{draft.connections.length}</span></button><button onClick={()=>setTab('builder')} className={`h-10 min-w-0 px-1.5 sm:px-3 rounded-xl border text-[8px] sm:text-[9px] font-bold whitespace-nowrap flex items-center justify-center gap-1 ${tab==='builder'?'bg-black text-white':''}`}><Sparkles size={11} className="shrink-0"/><span>CRIAR API</span></button></div></header><main className="flex-1 min-h-0 overflow-y-auto p-4 sm:p-6">
 {tab==='catalog'&&<div className="max-w-6xl mx-auto"><div className="sticky top-0 z-10 bg-[#EEEDE9] pb-3"><div className="mb-2 flex items-center gap-2 rounded-xl border border-emerald-200 bg-emerald-50 px-3 py-2 text-[9px] text-emerald-900"><Check size={13} className="shrink-0"/><span><b>CATÁLOGO GRATUITO.</b> Sem cobrança automática: serviços com cota devem falhar ao atingir o limite, nunca migrar para plano pago.</span></div><div className="grid grid-cols-1 sm:grid-cols-[minmax(0,1fr)_auto] gap-2"><label className="relative min-w-0"><Search size={15} className="absolute left-3 top-3 text-neutral-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar IA, arte, cor, ícones, mapas, AR, áudio..." className="h-10 w-full rounded-xl border pl-9 pr-3"/></label><select value={category} onChange={e=>setCategory(e.target.value)} className="h-10 w-full sm:w-auto sm:max-w-[18rem] rounded-xl border px-3 bg-white">{categories.map(c=><option key={c}>{c}</option>)}</select></div></div><div className="grid sm:grid-cols-2 xl:grid-cols-3 gap-3">{filtered.map(entry=><div key={entry.id} className="rounded-2xl border bg-white p-4 flex flex-col"><div className="flex items-start justify-between gap-2"><div><div className="text-[8px] font-mono text-neutral-500 uppercase">{entry.category}</div><b className="block mt-1">{entry.name}</b></div><span className="shrink-0 rounded-full bg-neutral-100 px-2 py-1 text-[7px] font-bold">{badge(entry.costModel)}</span></div><p className="mt-2 text-[10px] text-neutral-600 flex-1">{entry.summary}</p><div className="mt-3 grid grid-cols-2 gap-2"><button onClick={()=>setSelected(entry)} className="h-9 min-w-0 rounded-xl border px-2 text-[8px] sm:text-[9px] font-bold whitespace-nowrap">COMO USAR</button><button disabled={integratedIds.has(entry.id)} onClick={()=>integrate(entry)} className="h-9 min-w-0 rounded-xl bg-black px-2 text-white text-[8px] sm:text-[9px] font-bold whitespace-nowrap disabled:bg-neutral-200 disabled:text-neutral-500">{integratedIds.has(entry.id)?'INTEGRADA':'+ INCORPORAR'}</button></div></div>)}</div></div>}
 {tab==='integrated'&&<div className="max-w-5xl mx-auto space-y-3">{draft.connections.length===0&&<div className="rounded-2xl border border-dashed bg-white p-8 text-center text-sm text-neutral-500">Nenhuma API incorporada. Vá em Explorar ou crie uma.</div>}{draft.connections.map(item=><div key={item.id} className="rounded-2xl border bg-white p-4"><div className="flex items-start gap-3"><div className={`mt-1 h-3 w-3 rounded-full ${item.status==='configured'?'bg-emerald-500':item.status==='error'?'bg-red-500':'bg-amber-400'}`}/><div className="min-w-0 flex-1"><div className="text-[8px] font-mono text-neutral-500">{item.category}</div><b>{item.name}</b><p className="mt-1 text-[10px] text-neutral-600">{item.summary}</p><div className="mt-2 flex flex-wrap gap-1">{item.capabilities.map(c=><span key={c} className="rounded-full bg-neutral-100 px-2 py-1 text-[8px]">{c}</span>)}</div>{item.envVars.length>0&&<div className="mt-3 rounded-xl bg-amber-50 p-3"><div className="text-[9px] font-bold flex items-center gap-1"><KeyRound size={12}/> VARIÁVEIS NECESSÁRIAS</div>{item.envVars.map(v=><code key={v} className="mt-1 block text-[9px]">{v}=</code>)}<div className="mt-1 text-[9px] text-neutral-600">Vercel → Project → Settings → Environment Variables → adicionar → redeploy. Nunca coloque o valor secreto no frontend.</div></div>}{item.customSpec&&<div className="mt-3 rounded-xl border p-3"><div className="text-[9px] font-bold">ENDPOINTS GERADOS</div>{item.customSpec.endpoints.map((e,i)=><div key={i} className="mt-1 text-[9px] font-mono"><b>{e.method}</b> {e.path} — {e.purpose}</div>)}{item.customSpec.code&&<button onClick={()=>downloadCode(item)} className="mt-3 h-9 px-3 rounded-xl bg-black text-white text-[9px] font-bold flex items-center gap-2"><Download size={12}/> BAIXAR {item.customSpec.fileName||'API'}</button>}</div>}</div><div className="flex flex-col gap-2">{item.docsUrl&&<a href={item.docsUrl} target="_blank" rel="noreferrer" className="h-9 w-9 rounded-xl border flex items-center justify-center"><ExternalLink size={14}/></a>}<button onClick={()=>remove(item.id)} className="h-9 w-9 rounded-xl border border-red-200 text-red-600 flex items-center justify-center"><X size={14}/></button></div></div></div>)}</div>}
 {tab==='builder'&&<div className="max-w-4xl mx-auto grid lg:grid-cols-2 gap-4"><div className="rounded-2xl border bg-white p-4"><div className="flex items-center gap-2"><Code2 size={16}/><b>Arquiteto de API</b></div><p className="mt-2 text-[10px] text-neutral-600">Descreva o que precisa entrar e sair. O sistema prioriza as APIs já incorporadas e só pode propor integrações gratuitas, open source, self-hosted ou com cota gratuita sem faturamento automático.</p><div className="mt-3 flex gap-2 items-start"><textarea value={draft.builderPrompt||''} onChange={e=>setDraft({...draft,builderPrompt:e.target.value})} className="min-h-44 min-w-0 flex-1 rounded-xl border p-3 text-sm" placeholder="Ex.: quero uma API /api/artista?q= que busque uma pessoa no Wikidata, recupere trabalhos relacionados e devolva JSON normalizado..."/><VoiceDictationButton onText={t=>setDraft(d=>({...d,builderPrompt:`${d.builderPrompt||''}${d.builderPrompt?' ':''}${t}`}))}/></div><button onClick={()=>void createApi()} disabled={busy} className="mt-3 h-11 w-full rounded-xl bg-black text-white text-[10px] font-bold flex items-center justify-center gap-2">{busy?<Loader2 size={14} className="animate-spin"/>:<Sparkles size={14}/>} GERAR ESPECIFICAÇÃO + CÓDIGO</button>{error&&<div className="mt-3 rounded-xl bg-red-50 border border-red-200 p-3 text-xs text-red-700">{error}</div>}</div><div className="rounded-2xl border bg-white p-4"><b>Resultado</b>{!builderResult?<div className="mt-6 text-center text-sm text-neutral-400">A especificação aparecerá aqui.</div>:<div className="mt-3"><div className="text-[8px] font-mono text-neutral-500">{builderResult.fileName}</div><b className="text-lg">{builderResult.name}</b><p className="mt-1 text-[10px] text-neutral-600">{builderResult.summary}</p><div className="mt-3 space-y-1">{(builderResult.endpoints||[]).map((e:any,i:number)=><div key={i} className="rounded-lg bg-neutral-100 px-2 py-2 text-[9px] font-mono"><b>{e.method}</b> {e.path}<div className="font-sans text-neutral-500">{e.purpose}</div></div>)}</div>{builderResult.code&&<pre className="mt-3 max-h-80 overflow-auto rounded-xl bg-[#111] text-white p-3 text-[8px]">{builderResult.code}</pre>}<button onClick={addGenerated} className="mt-3 h-10 w-full rounded-xl bg-black text-white text-[9px] font-bold"><Plus size={12} className="inline mr-1"/> INCORPORAR AO PROJETO</button></div>}</div></div>}
 </main>{selected&&<div className="fixed inset-0 z-[150] bg-black/45 p-3 sm:p-8 flex items-end sm:items-center justify-center" onClick={()=>setSelected(null)}><div className="w-full max-w-2xl max-h-[90vh] overflow-auto rounded-t-3xl sm:rounded-3xl bg-white p-5" onClick={e=>e.stopPropagation()}><div className="flex items-start gap-3"><div className="flex-1"><div className="text-[9px] font-mono text-neutral-500">{selected.category} · {badge(selected.costModel)}</div><b className="text-xl">{selected.name}</b></div><button onClick={()=>setSelected(null)} className="h-10 w-10 rounded-xl border flex items-center justify-center"><X size={16}/></button></div><p className="mt-3 text-sm text-neutral-600">{selected.summary}</p><div className="mt-4 rounded-xl bg-neutral-100 p-3"><b className="text-[10px]">AUTENTICAÇÃO</b><div className="text-xs mt-1">{selected.auth}</div>{selected.envVars.map(v=><code key={v} className="block mt-1 text-[10px]">{v}=</code>)}</div><div className="mt-4"><b className="text-[10px]">PARA RODAR</b>{selected.setup.map((s,i)=><div key={i} className="mt-2 flex gap-2 text-xs"><span className="h-5 w-5 rounded-full bg-black text-white flex items-center justify-center text-[8px] shrink-0">{i+1}</span>{s}</div>)}</div>{selected.compatibility&&<div className="mt-4 rounded-xl border border-amber-200 bg-amber-50 p-3 text-xs">Compatibilidade: {selected.compatibility}</div>}{selected.caution&&<div className="mt-2 rounded-xl border border-amber-200 bg-amber-50 p-3 text-xs">{selected.caution}</div>}<div className="mt-5 flex gap-2"><a href={selected.docsUrl} target="_blank" rel="noreferrer" className="h-11 flex-1 rounded-xl border flex items-center justify-center gap-2 text-[10px] font-bold"><BookOpen size={14}/> DOCUMENTAÇÃO</a><button onClick={()=>{integrate(selected);setSelected(null)}} disabled={integratedIds.has(selected.id)} className="h-11 flex-1 rounded-xl bg-black text-white text-[10px] font-bold disabled:bg-neutral-200">{integratedIds.has(selected.id)?'JÁ INTEGRADA':'INCORPORAR'}</button></div></div></div>}</div>
}
