import { FontPreview, getFontshareFamilies, getGoogleFontFamilies, loadGraphicFont } from '../lib/graphicFonts';
import { StudioWorkspace } from './StudioWorkspace';
import StudioAreaGuide from './StudioAreaGuide';
import React, { useEffect, useMemo, useState } from 'react';
import { CheckCircle2, Eye, Plus, RefreshCw, Save, Search, ShieldCheck, Trash2, Type, X } from 'lucide-react';
import { DesignColorToken, DesignSystemDocument, DesignTypeToken, VisualIdentityDocument } from '../types';

interface DesignSystemStudioProps {
  document: DesignSystemDocument;
  title?: string;
  canEdit?: boolean;
  onSave: (document: DesignSystemDocument) => void;
  onClose: () => void;
  visualIdentitySuggestion?: VisualIdentityDocument;
}

const FALLBACK_FONTS = ['Inter','Roboto','Open Sans','Lato','Montserrat','Poppins','Nunito','Raleway','Merriweather','Playfair Display','Source Sans 3','Source Serif 4','IBM Plex Sans','IBM Plex Serif','IBM Plex Mono','Space Grotesk','DM Sans','DM Serif Display','Work Sans','Ubuntu','Oswald','Bebas Neue','Libre Baskerville','Crimson Text','Fira Sans','Fira Mono','Noto Sans','Noto Serif','Manrope','Mulish','Archivo','Archivo Black','Barlow','Cabin','Karla','Rubik','Quicksand','Josefin Sans','PT Sans','PT Serif'];
const makeId=(p:string)=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;
const normalizeHex=(value:string,fallback='#000000')=>{const c=String(value||'').trim().replace(/^#/,'').toUpperCase();if(/^[0-9A-F]{3}$/.test(c))return `#${c.split('').map(x=>x+x).join('')}`;if(/^[0-9A-F]{6}$/.test(c))return `#${c}`;return fallback;};
const hslToHex=(h:number,s:number,l:number)=>{s/=100;l/=100;const c=(1-Math.abs(2*l-1))*s,x=c*(1-Math.abs(((h/60)%2)-1)),m=l-c/2;let r=0,g=0,b=0;if(h<60)[r,g,b]=[c,x,0];else if(h<120)[r,g,b]=[x,c,0];else if(h<180)[r,g,b]=[0,c,x];else if(h<240)[r,g,b]=[0,x,c];else if(h<300)[r,g,b]=[x,0,c];else[r,g,b]=[c,0,x];const p=(v:number)=>Math.round((v+m)*255).toString(16).padStart(2,'0');return `#${p(r)}${p(g)}${p(b)}`.toUpperCase();};
const COLOR_LIBRARY=[...Array.from({length:24},(_,i)=>i*15).flatMap(h=>[24,34,44,54,64,74,84].map(l=>hslToHex(h,82,l))),...Array.from({length:13},(_,i)=>{const v=Math.round(i/12*255).toString(16).padStart(2,'0');return `#${v}${v}${v}`.toUpperCase();})];

export function designSystemFromIdentity(identity?: VisualIdentityDocument, base?: DesignSystemDocument): DesignSystemDocument {
  const fallback:DesignSystemDocument=base||{
    name:'Design System do projeto',primaryFont:'Inter',fontFamilies:{display:'Inter',text:'Inter',notes:'IBM Plex Mono'},
    colors:[{id:makeId('color'),name:'Brand',value:'#111111',role:'brand'},{id:makeId('color'),name:'Accent',value:'#7C3AED',role:'accent'},{id:makeId('color'),name:'Surface',value:'#FFFFFF',role:'surface'},{id:makeId('color'),name:'Text',value:'#111111',role:'text'}],
    typography:[
      {id:makeId('type'),name:'Display',family:'Inter',familyRole:'display',size:48,weight:700,lineHeight:1.05,letterSpacing:-0.02,wordSpacing:0},
      {id:makeId('type'),name:'Heading',family:'Inter',familyRole:'display',size:28,weight:700,lineHeight:1.15,letterSpacing:-0.01,wordSpacing:0},
      {id:makeId('type'),name:'Body',family:'Inter',familyRole:'text',size:16,weight:400,lineHeight:1.5,letterSpacing:0,wordSpacing:0},
      {id:makeId('type'),name:'Notes',family:'IBM Plex Mono',familyRole:'notes',size:12,weight:500,lineHeight:1.45,letterSpacing:0.02,wordSpacing:0},
    ],spacing:[4,8,12,16,24,32,48,64],radii:[0,4,8,12,16,24,999],layoutSpacing:{pagePadding:24,sectionGap:32,componentGap:16,controlHeight:44},updatedAt:new Date().toISOString()
  };
  if(!identity)return fallback;
  const roleFor=(index:number):DesignColorToken['role']=>index===0?'brand':index===1?'accent':index===2?'surface':index===3?'text':'custom';
  const colors=identity.palette.slice(0,8).map((c,index)=>({id:makeId('color'),name:c.name||`Cor ${index+1}`,value:c.color,role:roleFor(index)}));
  const ff={display:identity.typography.display||fallback.fontFamilies?.display||'Inter',text:identity.typography.text||fallback.fontFamilies?.text||'Inter',notes:identity.typography.accent||fallback.fontFamilies?.notes||'IBM Plex Mono'};
  return {...fallback,name:identity.brandName&&identity.brandName!=='Nome da marca'?`Design System · ${identity.brandName}`:fallback.name,primaryFont:ff.text,fontFamilies:ff,colors:colors.length>=4?colors:fallback.colors,typography:fallback.typography.map(t=>({...t,family:t.familyRole==='display'?ff.display:t.familyRole==='notes'?ff.notes:ff.text})),updatedAt:new Date().toISOString()};
}

export const blankDesignSystem=(identity?:VisualIdentityDocument):DesignSystemDocument=>designSystemFromIdentity(identity);

const loadAnyFont=(family:string)=>{void loadGraphicFont(family).catch(()=>{})};
const luminance=(hex:string)=>{const c=normalizeHex(hex).slice(1);const rgb=[0,2,4].map(i=>parseInt(c.slice(i,i+2),16)/255).map(v=>v<=.03928?v/12.92:Math.pow((v+.055)/1.055,2.4));return .2126*rgb[0]+.7152*rgb[1]+.0722*rgb[2];};
const contrastRatio=(a:string,b:string)=>{const x=luminance(a),y=luminance(b);return (Math.max(x,y)+.05)/(Math.min(x,y)+.05);};
type Vision='normal'|'protanopia'|'deuteranopia'|'tritanopia'|'achromatopsia';
const matrices:Record<Exclude<Vision,'normal'>,number[][]>={
  protanopia:[[.567,.433,0],[.558,.442,0],[0,.242,.758]],
  deuteranopia:[[.625,.375,0],[.7,.3,0],[0,.3,.7]],
  tritanopia:[[.95,.05,0],[0,.433,.567],[0,.475,.525]],
  achromatopsia:[[.299,.587,.114],[.299,.587,.114],[.299,.587,.114]],
};
const simulateColor=(hex:string,mode:Vision)=>{const n=normalizeHex(hex);if(mode==='normal')return n;const rgb=[1,3,5].map(i=>parseInt(n.slice(i,i+2),16));const m=matrices[mode];const out=m.map(row=>Math.max(0,Math.min(255,Math.round(row[0]*rgb[0]+row[1]*rgb[1]+row[2]*rgb[2]))));return `#${out.map(v=>v.toString(16).padStart(2,'0')).join('')}`.toUpperCase();};

function HexField({value,onChange,disabled}:{value:string;onChange:(v:string)=>void;disabled?:boolean}){const safe=normalizeHex(value);return <div className="flex gap-2"><input aria-label="Selecionar cor" type="color" value={safe} disabled={disabled} onChange={e=>onChange(e.target.value.toUpperCase())} className="h-11 w-12 shrink-0 rounded-lg border border-black/10 p-1 bg-white"/><input value={value} disabled={disabled} onChange={e=>onChange(e.target.value)} onBlur={e=>onChange(normalizeHex(e.target.value,safe))} className="h-11 min-w-0 flex-1 rounded-xl border border-black/10 px-3 font-mono text-xs uppercase" placeholder="#FF13F0"/></div>}

export function DesignSystemPreview({document,className=''}:{document:DesignSystemDocument;className?:string}){
  const f=document.fontFamilies||{display:document.primaryFont,text:document.primaryFont,notes:document.primaryFont};
  useEffect(()=>{Object.values(f).forEach(loadAnyFont)},[f.display,f.text,f.notes]);
  return <div className={`bg-white p-4 overflow-hidden ${className}`}><div className="text-[9px] font-mono uppercase tracking-widest text-neutral-400">Design System</div><div className="mt-1 text-lg font-bold ds-preview-title" style={{fontFamily:f.display}}>{document.name}</div><div className="mt-4 flex gap-1.5 flex-wrap">{document.colors.slice(0,8).map(c=><span key={c.id} className="h-8 w-8 rounded-lg border border-black/10" style={{background:c.value}} title={`${c.name}: ${c.value}`}/>)}</div><div className="mt-4 space-y-2"><div className="text-xl font-bold" style={{fontFamily:f.display}}>Display · {f.display}</div><div className="text-sm" style={{fontFamily:f.text}}>Texto · {f.text} — Aa Bb Cc 0123456789</div><div className="text-xs text-neutral-500" style={{fontFamily:f.notes}}>Notas · {f.notes}</div></div><div className="mt-4 flex flex-wrap gap-1.5">{document.spacing.slice(0,8).map(v=><span key={v} className="rounded-full bg-neutral-100 px-2 py-1 text-[9px] font-mono">{v}px</span>)}</div></div>;
}

export default function DesignSystemStudio({document,title='Design System',canEdit=true,onSave,onClose,visualIdentitySuggestion}:DesignSystemStudioProps){
  const initial=JSON.parse(JSON.stringify(document)) as DesignSystemDocument;
  initial.fontFamilies ||= {display:initial.primaryFont||'Inter',text:initial.primaryFont||'Inter',notes:'IBM Plex Mono'};
  initial.layoutSpacing ||= {pagePadding:24,sectionGap:32,componentGap:16,controlHeight:44};
  initial.typography=(initial.typography||[]).map((t,i)=>({...t,letterSpacing:t.letterSpacing??0,wordSpacing:t.wordSpacing??0,familyRole:t.familyRole||(i<2?'display':i===initial.typography.length-1?'notes':'text')}));
  const [draft,setDraft]=useState(initial);const [fontSearch,setFontSearch]=useState('');const [fonts,setFonts]=useState(FALLBACK_FONTS);const [fontStatus,setFontStatus]=useState<'idle'|'loading'|'google'|'fontshare'|'mixed'|'fallback'>('idle');const [fontProvider,setFontProvider]=useState<'all'|'google'|'fontshare'>('all');const [fontshareNames,setFontshareNames]=useState<Set<string>>(new Set());const [fontTarget,setFontTarget]=useState<'display'|'text'|'notes'>('display');const [fg,setFg]=useState(draft.colors.find(c=>c.role==='text')?.value||'#111111');const [bg,setBg]=useState(draft.colors.find(c=>c.role==='surface')?.value||'#FFFFFF');const [vision,setVision]=useState<Vision>('normal');
  const ratio=useMemo(()=>contrastRatio(normalizeHex(fg),normalizeHex(bg)),[fg,bg]);
  useEffect(()=>{Object.values(draft.fontFamilies!).forEach(loadAnyFont)},[draft.fontFamilies?.display,draft.fontFamilies?.text,draft.fontFamilies?.notes]);
  useEffect(()=>{let cancelled=false;const timer=window.setTimeout(async()=>{setFontStatus('loading');try{const q=fontSearch.trim().toLowerCase();const wantGoogle=fontProvider!=='fontshare';const wantFontshare=fontProvider!=='google';const [google,fontshare]=await Promise.all([wantGoogle?getGoogleFontFamilies():Promise.resolve([]),wantFontshare?getFontshareFamilies():Promise.resolve([])]);if(cancelled)return;const fsNames=fontshare.map(item=>item.family);setFontshareNames(new Set(fsNames));const combined=[...new Set([...fsNames,...google])].filter(f=>!q||f.toLowerCase().includes(q)).sort((a,b)=>a.localeCompare(b));setFonts(combined);setFontStatus(fontProvider==='fontshare'?'fontshare':fontProvider==='google'?'google':'mixed')}catch{if(!cancelled){const q=fontSearch.toLowerCase();setFonts(FALLBACK_FONTS.filter(f=>!q||f.toLowerCase().includes(q)));setFontStatus('fallback')}}},180);return()=>{cancelled=true;clearTimeout(timer)}},[fontSearch,fontProvider]);
  const patchColor=(id:string,p:Partial<DesignColorToken>)=>setDraft(d=>({...d,colors:d.colors.map(c=>c.id===id?{...c,...p}:c)}));
  const patchType=(id:string,p:Partial<DesignTypeToken>)=>setDraft(d=>({...d,typography:d.typography.map(t=>t.id===id?{...t,...p}:t)}));
  const selectFont=(family:string)=>{loadAnyFont(family);setDraft(d=>{const ff={...(d.fontFamilies||{display:d.primaryFont,text:d.primaryFont,notes:d.primaryFont}),[fontTarget]:family};return {...d,primaryFont:ff.text,fontFamilies:ff,typography:d.typography.map(t=>(t.familyRole||'text')===fontTarget?{...t,family}:t)}})};
  const applyIdentitySuggestion=()=>{if(!visualIdentitySuggestion)return;setDraft(current=>designSystemFromIdentity(visualIdentitySuggestion,current));};
  return <div className="design-system-editor studio-editor fixed inset-0 z-[125] bg-[#F2F1ED] flex flex-col canvas-control atelier-studio" onPointerDown={e=>e.stopPropagation()}>
    <header className="shrink-0 min-h-16 bg-white border-b border-black/10 px-3 sm:px-5 flex items-center gap-3" style={{paddingTop:'max(.35rem, env(safe-area-inset-top))'}}><button onClick={onClose} className="h-11 w-11 rounded-xl hover:bg-black/5 flex items-center justify-center"><X size={19}/></button><div className="min-w-0 flex-1"><div className="font-bold truncate">{title}</div><div className="text-[10px] font-mono text-neutral-500 uppercase">tokens · até 3 famílias · paleta · espaçamento · acessibilidade</div></div><StudioAreaGuide area="design-system"/><button disabled={!canEdit} onClick={()=>onSave({...draft,updatedAt:new Date().toISOString()})} className="h-11 px-4 rounded-xl bg-black text-white text-xs font-bold flex items-center gap-2 disabled:opacity-40"><Save size={15}/> SALVAR</button></header>
<StudioWorkspace tools={      <section className="min-h-0 overflow-y-auto p-4 sm:p-6 space-y-5">
        <div className="rounded-2xl bg-white border border-black/10 p-4"><label className="text-[9px] font-mono font-bold uppercase text-neutral-500">Nome do sistema</label><input value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})} className="mt-2 h-11 w-full rounded-xl border border-black/10 px-3 font-semibold"/></div>{visualIdentitySuggestion && <div className="rounded-2xl border-2 border-teal-700 bg-teal-50 p-4"><div className="flex items-start gap-3"><RefreshCw size={17} className="mt-0.5 text-teal-800"/><div className="min-w-0 flex-1"><div className="text-sm font-bold">Identidade visual disponível</div><div className="mt-1 text-[10px] text-teal-950/70">Use a paleta e as famílias tipográficas da identidade como sugestão inicial. Espaçamentos, raios e critérios de acessibilidade permanecem próprios do Design System.</div></div></div><button onClick={applyIdentitySuggestion} className="mt-3 h-10 w-full rounded-xl bg-teal-800 text-white text-[10px] font-bold">APLICAR IDENTIDADE → DESIGN SYSTEM</button></div>}
        <div className="rounded-2xl bg-white border border-black/10 p-4"><div className="flex items-start justify-between gap-3"><div><div className="text-sm font-bold">Paleta e HEX</div><div className="text-[10px] text-neutral-500">Cole, digite ou escolha qualquer HEX. Os tokens alimentam os demais módulos.</div></div><button onClick={()=>setDraft(d=>({...d,colors:[...d.colors,{id:makeId('color'),name:'Nova cor',value:'#7C3AED',role:'custom'}]}))} className="h-10 px-3 rounded-xl border border-black text-[10px] font-mono font-bold flex items-center gap-2"><Plus size={14}/> COR</button></div>
          <div className="ds-color-library mt-3 max-h-36 overflow-y-auto grid gap-1.5">{COLOR_LIBRARY.map((v,i)=><button key={`${v}-${i}`} onClick={()=>setDraft(d=>({...d,colors:[...d.colors,{id:makeId('color'),name:`Cor ${d.colors.length+1}`,value:v,role:'custom'}]}))} className="aspect-square min-h-6 rounded-md border border-black/10" style={{background:v}} title={v}/>)}</div>
          <div className="mt-4 grid md:grid-cols-2 2xl:grid-cols-3 gap-3">{draft.colors.map(c=><div key={c.id} className="rounded-xl border border-black/10 p-3"><div className="flex gap-2 items-start"><div className="min-w-0 flex-1"><input value={c.name} onChange={e=>patchColor(c.id,{name:e.target.value})} className="w-full text-xs font-bold outline-none mb-2"/><HexField value={c.value} onChange={v=>patchColor(c.id,{value:v})}/></div><button disabled={draft.colors.length<=2} onClick={()=>setDraft(d=>({...d,colors:d.colors.filter(x=>x.id!==c.id)}))} className="h-9 w-9 rounded-lg text-red-600 disabled:opacity-20 flex items-center justify-center"><Trash2 size={14}/></button></div><select value={c.role||'custom'} onChange={e=>patchColor(c.id,{role:e.target.value as any})} className="mt-2 h-9 w-full rounded-lg border border-black/10 px-2 text-[10px]"><option value="brand">Brand</option><option value="accent">Accent</option><option value="surface">Surface</option><option value="text">Text</option><option value="success">Success</option><option value="warning">Warning</option><option value="danger">Danger</option><option value="custom">Custom</option></select></div>)}</div>
        </div>
        <div className="rounded-2xl bg-white border border-black/10 p-4"><div className="flex items-start justify-between gap-3"><div><div className="text-sm font-bold flex items-center gap-2"><Type size={15}/> Famílias tipográficas</div><div className="text-[10px] text-neutral-500">No máximo 3: Display, Texto e Notas. Agora o catálogo combina <b>Google Fonts + Fontshare</b>; o Fontshare entra direto pelo CDN gratuito e sem chave.</div></div><span className="text-[9px] font-mono rounded-full bg-neutral-100 px-2 py-1 whitespace-nowrap">{fontStatus==='mixed'?'GOOGLE + FONTSHARE':fontStatus==='fontshare'?'FONTSHARE':fontStatus==='google'?'GOOGLE':fontStatus==='loading'?'BUSCANDO…':'FALLBACK'}</span></div>
          <div className="mt-3 grid grid-cols-3 gap-2">{(['display','text','notes'] as const).map(role=><button key={role} onClick={()=>setFontTarget(role)} className={`rounded-xl border p-3 text-left ${fontTarget===role?'bg-black text-white border-black':'border-black/10'}`}><div className="text-[9px] font-mono uppercase">{role==='display'?'Display':role==='text'?'Texto':'Notas'}</div><FontPreview family={draft.fontFamilies?.[role]||'Inter'} className="mt-1 block text-xs font-bold truncate">{draft.fontFamilies?.[role]}</FontPreview></button>)}</div>
          <div className="mt-3 grid grid-cols-3 gap-2">{([['all','TODAS'],['google','GOOGLE'],['fontshare','FONTSHARE']] as const).map(([id,label])=><button key={id} type="button" onClick={()=>setFontProvider(id)} className={`h-9 rounded-xl border text-[9px] font-bold ${fontProvider===id?'bg-black text-white border-black':'bg-white border-black/10'}`}>{label}</button>)}</div>
          <div className="mt-3 relative"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-neutral-400"/><input value={fontSearch} onChange={e=>setFontSearch(e.target.value)} placeholder={`Buscar Google Fonts + Fontshare para ${fontTarget}…`} className="h-11 w-full rounded-xl border border-black/10 pl-9 pr-3"/></div><div className="mt-3 max-h-64 overflow-y-auto grid md:grid-cols-2 gap-2">{fonts.slice(0,300).map(f=><button key={f} onClick={()=>selectFont(f)} onMouseEnter={()=>loadAnyFont(f)} onFocus={()=>loadAnyFont(f)} className={`min-h-16 rounded-xl border px-3 py-2 text-left ${draft.fontFamilies?.[fontTarget]===f?'bg-black text-white border-black':'border-black/10'}`}><div className="flex items-center justify-between gap-2"><FontPreview family={f} className="text-sm truncate">{f}</FontPreview><span className={`text-[7px] font-mono rounded-full px-1.5 py-0.5 ${draft.fontFamilies?.[fontTarget]===f?'bg-white/15':'bg-neutral-100 text-neutral-500'}`}>{fontshareNames.has(f)?'FONTSHARE':'GOOGLE'}</span></div><FontPreview family={f} className="mt-1 block text-[11px] opacity-70">Aa Bb Cc 0123 · Design para projetos</FontPreview></button>)}</div>
          <div className="mt-3 rounded-xl bg-[#F4F3EF] p-3 text-[9px] text-neutral-600">Fontshare é usado sem chave. O sistema não baixa nem redistribui arquivos de fonte: carrega a família pelo CSS/CDN do serviço para prévia e uso no projeto.</div>
        </div>
        <div className="rounded-2xl bg-white border border-black/10 p-4"><div className="text-sm font-bold">Escala tipográfica · kerning/tracking</div><div className="text-[10px] text-neutral-500 mt-1">Aqui “kerning” é controlado de forma prática por letter-spacing/tracking. Entrelinha e espaço entre palavras também ficam explícitos.</div><div className="mt-3 space-y-3">{draft.typography.map(t=><div key={t.id} className="rounded-xl border border-black/10 p-3"><div className="ds-type-controls grid gap-2"><div><input value={t.name} onChange={e=>patchType(t.id,{name:e.target.value})} className="w-full text-[10px] font-mono uppercase text-neutral-500 outline-none"/><div className="ds-type-sample mt-1" style={{fontFamily:t.family,fontSize:Math.min(t.size,36),fontWeight:t.weight,lineHeight:t.lineHeight,letterSpacing:`${t.letterSpacing||0}em`,wordSpacing:`${t.wordSpacing||0}em`}}>Design que pensa e faz</div></div><label className="text-[9px] font-mono text-neutral-500">FAMÍLIA<select value={t.familyRole||'text'} onChange={e=>{const role=e.target.value as any;patchType(t.id,{familyRole:role,family:draft.fontFamilies?.[role]||draft.primaryFont})}} className="mt-1 h-9 w-full rounded-lg border border-black/10 px-2"><option value="display">Display</option><option value="text">Texto</option><option value="notes">Notas</option></select></label><label className="text-[9px] font-mono text-neutral-500">PESO<select value={t.weight} onChange={e=>patchType(t.id,{weight:Number(e.target.value)})} className="mt-1 h-9 w-full rounded-lg border border-black/10 px-2">{[300,400,500,600,700,800,900].map(w=><option key={w}>{w}</option>)}</select></label></div><div className="mt-2 grid grid-cols-2 md:grid-cols-4 gap-2"><label className="text-[9px] font-mono text-neutral-500">TAMANHO<input type="number" value={t.size} onChange={e=>patchType(t.id,{size:Number(e.target.value)})} className="mt-1 h-9 w-full rounded-lg border border-black/10 px-2"/></label><label className="text-[9px] font-mono text-neutral-500">ENTRELINHA<input type="number" step="0.05" value={t.lineHeight} onChange={e=>patchType(t.id,{lineHeight:Number(e.target.value)})} className="mt-1 h-9 w-full rounded-lg border border-black/10 px-2"/></label><label className="text-[9px] font-mono text-neutral-500">TRACKING (EM)<input type="number" step="0.01" value={t.letterSpacing||0} onChange={e=>patchType(t.id,{letterSpacing:Number(e.target.value)})} className="mt-1 h-9 w-full rounded-lg border border-black/10 px-2"/></label><label className="text-[9px] font-mono text-neutral-500">PALAVRAS (EM)<input type="number" step="0.01" value={t.wordSpacing||0} onChange={e=>patchType(t.id,{wordSpacing:Number(e.target.value)})} className="mt-1 h-9 w-full rounded-lg border border-black/10 px-2"/></label></div></div>)}</div></div>
        <div className="rounded-2xl bg-white border border-black/10 p-4"><div className="text-sm font-bold">Espaçamento do sistema</div><div className="mt-3 grid md:grid-cols-2 gap-3"><label className="text-[10px] font-mono text-neutral-500">ESCALA<input value={draft.spacing.join(', ')} onChange={e=>setDraft({...draft,spacing:e.target.value.split(',').map(Number).filter(Number.isFinite)})} className="mt-1 h-11 w-full rounded-xl border border-black/10 px-3"/></label><label className="text-[10px] font-mono text-neutral-500">RAIOS<input value={draft.radii.join(', ')} onChange={e=>setDraft({...draft,radii:e.target.value.split(',').map(Number).filter(Number.isFinite)})} className="mt-1 h-11 w-full rounded-xl border border-black/10 px-3"/></label></div><div className="mt-3 grid grid-cols-2 md:grid-cols-4 gap-2">{([['pagePadding','Padding da página'],['sectionGap','Entre seções'],['componentGap','Entre componentes'],['controlHeight','Altura controles']] as const).map(([k,l])=><label key={k} className="text-[9px] font-mono text-neutral-500">{l.toUpperCase()}<input type="number" value={draft.layoutSpacing?.[k]??0} onChange={e=>setDraft(d=>({...d,layoutSpacing:{...(d.layoutSpacing||{pagePadding:24,sectionGap:32,componentGap:16,controlHeight:44}),[k]:Number(e.target.value)}}))} className="mt-1 h-10 w-full rounded-lg border border-black/10 px-2"/></label>)}</div></div>
      </section>}>
      <aside className="min-h-0 overflow-y-auto border-t xl:border-t-0 xl:border-l border-black/10 bg-white p-4 space-y-5"><div><div className="text-[9px] font-mono uppercase tracking-widest text-neutral-500">Prévia viva</div><div className="mt-3 rounded-2xl border border-black/10 overflow-hidden"><DesignSystemPreview document={draft} className="min-h-64"/></div></div><div className="rounded-2xl border border-black/10 p-4"><div className="flex items-center gap-2 text-sm font-bold"><ShieldCheck size={16}/> Contraste WCAG</div><div className="ds-contrast-controls mt-3 grid gap-2"><div><div className="text-[9px] font-mono mb-1">TEXTO</div><HexField value={fg} onChange={setFg}/></div><div><div className="text-[9px] font-mono mb-1">FUNDO</div><HexField value={bg} onChange={setBg}/></div></div><div className="mt-3 rounded-xl p-4 border" style={{background:normalizeHex(bg),color:normalizeHex(fg),fontFamily:draft.fontFamilies?.text}}>Texto de teste · legibilidade também é projeto.</div><div className="mt-3 flex justify-between text-xs"><span>CONTRASTE</span><strong>{ratio.toFixed(2)}:1</strong></div><div className="mt-2 grid grid-cols-3 gap-1 text-[9px] text-center"><span className={`rounded-lg py-2 ${ratio>=4.5?'bg-emerald-50 text-emerald-700':'bg-red-50 text-red-700'}`}>AA {ratio>=4.5?'✓':'×'}</span><span className={`rounded-lg py-2 ${ratio>=3?'bg-emerald-50 text-emerald-700':'bg-red-50 text-red-700'}`}>AA grande {ratio>=3?'✓':'×'}</span><span className={`rounded-lg py-2 ${ratio>=7?'bg-emerald-50 text-emerald-700':'bg-amber-50 text-amber-700'}`}>AAA {ratio>=7?'✓':'—'}</span></div></div><div className="rounded-2xl border border-black/10 p-4"><div className="flex items-center gap-2 text-sm font-bold"><Eye size={16}/> Simulação de daltonismo</div><div className="mt-2 grid grid-cols-2 gap-2">{([['normal','Visão comum'],['protanopia','Protanopia'],['deuteranopia','Deuteranopia'],['tritanopia','Tritanopia'],['achromatopsia','Acromatopsia']] as [Vision,string][]).map(([v,l])=><button key={v} onClick={()=>setVision(v)} className={`h-9 rounded-lg border text-[9px] font-bold ${vision===v?'bg-black text-white border-black':'border-black/10'}`}>{l}</button>)}</div><div className="mt-3 flex flex-wrap gap-2">{draft.colors.map(c=><div key={c.id} className="w-16"><div className="h-12 rounded-lg border border-black/10" style={{background:simulateColor(c.value,vision)}}/><div className="mt-1 text-[8px] font-mono truncate">{c.name}</div><div className="text-[8px] font-mono text-neutral-400">{simulateColor(c.value,vision)}</div></div>)}</div><div className="mt-3 text-[9px] text-neutral-500">Simulação aproximada para apoiar decisões; não substitui teste com pessoas nem critérios de contraste.</div></div><div className="rounded-2xl bg-[#F4F3EF] p-4 text-[10px] text-neutral-600"><CheckCircle2 size={15} className="mb-2"/>O Design System fica ligado ao projeto e pode alimentar wireframes, vídeo e futuras exportações.</div></aside>
    </StudioWorkspace>
  </div>;
}
