import React, { useRef, useState } from 'react';
import { X, Send, Image, Video, Loader2, Trash2, ExternalLink } from 'lucide-react';
import type { ThoughtNode, UserProfile, NodeComment, NodeAttachment } from '../types';
import { readStoredTursoSession } from '../lib/turso';

interface Props { node: ThoughtNode; user: UserProfile; onClose:()=>void; onChange:(node:ThoughtNode)=>void; }
export default function NodeCollaborationPanel({ node, user, onClose, onChange }: Props) {
  const [text,setText]=useState(''); const [uploading,setUploading]=useState(false); const [error,setError]=useState('');
  const fileRef=useRef<HTMLInputElement>(null);
  const comments=node.comments||[]; const attachments=node.attachments||[];
  function addComment(){ if(!text.trim())return; const c:NodeComment={id:`comment-${Date.now()}`,authorId:user.id,authorName:user.name,authorRole:user.role,text:text.trim(),createdAt:new Date().toISOString()}; onChange({...node,comments:[...comments,c]}); setText(''); }
  function removeComment(id:string){ onChange({...node,comments:comments.filter(c=>c.id!==id)}); }
  async function upload(file:File){ setUploading(true);setError(''); try{ const session=readStoredTursoSession(); if(!session) throw new Error('Faça login novamente.'); const r=await fetch('/api/upload',{method:'POST',headers:{Authorization:`Bearer ${session.token}`,'Content-Type':file.type,'X-File-Name':encodeURIComponent(file.name)},body:file}); const data=await r.json().catch(()=>({})); if(!r.ok)throw new Error(data.error||'Falha no upload.'); const a:NodeAttachment={id:`attachment-${Date.now()}`,url:data.url,name:file.name,type:file.type.startsWith('video/')?'video':'image',contentType:file.type,authorId:user.id,authorName:user.name,createdAt:new Date().toISOString()}; onChange({...node,attachments:[...attachments,a]}); }catch(e:any){setError(e.message)}finally{setUploading(false); if(fileRef.current)fileRef.current.value='';}}
  function removeAttachment(id:string){ onChange({...node,attachments:attachments.filter(a=>a.id!==id)}); }
  return <div className="fixed inset-0 z-[100] bg-black/30 flex justify-end" onClick={onClose}><aside className="w-full max-w-md h-full bg-white shadow-2xl flex flex-col" onClick={e=>e.stopPropagation()}>
    <header className="p-5 border-b flex items-start justify-between"><div><span className="text-[10px] font-mono uppercase text-neutral-400">Colaboração no card</span><h2 className="font-bold text-lg mt-1">{node.title||'Bloco de notas'}</h2></div><button onClick={onClose} className="p-2 rounded-lg hover:bg-black/5 cursor-pointer"><X size={18}/></button></header>
    <div className="flex-1 overflow-y-auto p-5 space-y-7">
      <section><h3 className="text-xs font-mono font-bold uppercase tracking-wider mb-3">Imagens e vídeos</h3><input ref={fileRef} type="file" accept="image/*,video/*" className="hidden" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0])}/><button onClick={()=>fileRef.current?.click()} disabled={uploading} className="w-full border-2 border-dashed rounded-2xl p-4 flex items-center justify-center gap-2 text-xs font-bold cursor-pointer disabled:opacity-50">{uploading?<Loader2 className="animate-spin" size={16}/>:<><Image size={16}/><Video size={16}/></>} {uploading?'Enviando...':'Adicionar imagem ou vídeo'}</button>{error&&<p className="text-xs text-red-600 mt-2">{error}</p>}
      <div className="grid grid-cols-2 gap-3 mt-3">{attachments.map(a=><div key={a.id} className="border rounded-xl overflow-hidden bg-[#F7F7F5]">{a.type==='image'?<img src={a.url} alt={a.name} className="w-full h-28 object-cover"/>:<video src={a.url} controls className="w-full h-28 object-cover"/>}<div className="p-2 flex items-center justify-between gap-2"><a href={a.url} target="_blank" rel="noreferrer" className="text-[10px] truncate flex items-center gap-1"><ExternalLink size={10}/>{a.name}</a>{a.authorId===user.id&&<button onClick={()=>removeAttachment(a.id)} className="text-red-500 cursor-pointer"><Trash2 size={13}/></button>}</div></div>)}</div></section>
      <section><h3 className="text-xs font-mono font-bold uppercase tracking-wider mb-3">Comentários ({comments.length})</h3><div className="space-y-3">{comments.map(c=><article key={c.id} className="bg-[#F7F7F5] rounded-2xl p-3"><div className="flex justify-between gap-2"><div><strong className="text-xs">{c.authorName}</strong><span className="text-[9px] font-mono uppercase text-neutral-400 ml-2">{c.authorRole==='advisor'?'Professora':c.authorRole}</span></div>{c.authorId===user.id&&<button onClick={()=>removeComment(c.id)} className="text-red-500 cursor-pointer"><Trash2 size={13}/></button>}</div><p className="text-sm mt-2 whitespace-pre-wrap">{c.text}</p><time className="text-[9px] text-neutral-400 mt-2 block">{new Date(c.createdAt).toLocaleString('pt-BR')}</time></article>)}{comments.length===0&&<p className="text-xs text-neutral-400">Ainda não há comentários neste card.</p>}</div></section>
    </div>
    <footer className="p-4 border-t"><div className="flex gap-2"><textarea value={text} onChange={e=>setText(e.target.value)} rows={2} placeholder="Escreva uma orientação ou comentário..." className="flex-1 border rounded-xl p-3 text-sm resize-none outline-none focus:border-black"/><button onClick={addComment} disabled={!text.trim()} className="w-12 rounded-xl bg-black text-white flex items-center justify-center cursor-pointer disabled:opacity-30"><Send size={17}/></button></div></footer>
  </aside></div>
}
