import ResizableStudioGrid from './ResizableStudioGrid';
import StudioAreaGuide from './StudioAreaGuide';
import React, { useRef, useState } from 'react';
import { Headphones, Link, Loader2, Play, Plus, Save, Trash2, Upload, Volume2, X } from 'lucide-react';
import { SoundCue, SoundDocument, SoundPreset } from '../types';
import { ensureTursoSession } from '../lib/turso';

interface Props { document: SoundDocument; title?: string; canEdit?: boolean; onSave:(document:SoundDocument)=>void; onClose:()=>void; }
const makeId=()=>`sound-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;
const PRESETS:Array<{id:SoundPreset;label:string;frequency:number;duration:number;hint:string}>=[
  {id:'click',label:'Click',frequency:880,duration:.08,hint:'ação curta / botão'},
  {id:'pop',label:'Pop',frequency:520,duration:.16,hint:'bolha / microinteração'},
  {id:'success',label:'Sucesso',frequency:660,duration:.28,hint:'confirmação positiva'},
  {id:'error',label:'Erro',frequency:220,duration:.28,hint:'falha ou bloqueio'},
  {id:'whoosh',label:'Whoosh',frequency:340,duration:.42,hint:'transição / entrada'},
  {id:'notification',label:'Notificação',frequency:740,duration:.32,hint:'novo evento'},
];
export const blankSound=():SoundDocument=>({title:'Sonoridade do projeto',masterVolume:.8,cues:PRESETS.slice(0,3).map((p)=>({id:makeId(),name:p.label,source:'synth',preset:p.id,volume:.7,duration:p.duration,frequency:p.frequency,trigger:'click'}))});

export function SoundPreview({document,className=''}:{document:SoundDocument;className?:string}){
  return <div className={`bg-[#111] text-white p-4 ${className}`}><div className="flex items-center gap-2 text-xs font-bold"><Volume2 size={15}/> {document.title}</div><div className="mt-3 flex flex-wrap gap-2">{document.cues.slice(0,6).map((cue)=><span key={cue.id} className="rounded-full border border-white/20 px-2 py-1 text-[9px] font-mono">{cue.name}</span>)}</div></div>;
}

function playSynth(cue:SoundCue,master:number){
  const Ctx=(window.AudioContext||(window as any).webkitAudioContext); if(!Ctx)return;
  const ctx=new Ctx(); const now=ctx.currentTime; const volume=Math.max(0,Math.min(1,cue.volume*master));
  const tone=(freq:number,start:number,dur:number,type:OscillatorType='sine')=>{const osc=ctx.createOscillator();const gain=ctx.createGain();osc.type=type;osc.frequency.setValueAtTime(freq,now+start);gain.gain.setValueAtTime(.0001,now+start);gain.gain.exponentialRampToValueAtTime(Math.max(.001,volume*.24),now+start+.01);gain.gain.exponentialRampToValueAtTime(.0001,now+start+dur);osc.connect(gain);gain.connect(ctx.destination);osc.start(now+start);osc.stop(now+start+dur+.02);};
  const p=cue.preset||'click';
  if(p==='success'){tone(cue.frequency,0,cue.duration*.55);tone(cue.frequency*1.26,cue.duration*.42,cue.duration*.55)}
  else if(p==='error'){tone(cue.frequency,0,cue.duration*.52,'sawtooth');tone(cue.frequency*.82,cue.duration*.44,cue.duration*.55,'sawtooth')}
  else if(p==='notification'){tone(cue.frequency,0,cue.duration*.48);tone(cue.frequency*1.5,cue.duration*.5,cue.duration*.45)}
  else if(p==='whoosh'){const osc=ctx.createOscillator();const gain=ctx.createGain();osc.type='sine';osc.frequency.setValueAtTime(cue.frequency*.45,now);osc.frequency.exponentialRampToValueAtTime(cue.frequency*2.1,now+cue.duration);gain.gain.setValueAtTime(.0001,now);gain.gain.exponentialRampToValueAtTime(Math.max(.001,volume*.15),now+.05);gain.gain.exponentialRampToValueAtTime(.0001,now+cue.duration);osc.connect(gain);gain.connect(ctx.destination);osc.start(now);osc.stop(now+cue.duration+.02)}
  else tone(cue.frequency,0,cue.duration,p==='click'?'square':'sine');
  window.setTimeout(()=>ctx.close().catch(()=>{}),Math.max(500,cue.duration*1800));
}

export default function SoundStudio({document,title='Sonoridade',canEdit=true,onSave,onClose}:Props){
  const [draft,setDraft]=useState<SoundDocument>(()=>JSON.parse(JSON.stringify(document)));
  const [selectedId,setSelectedId]=useState(draft.cues[0]?.id||'');
  const [uploading,setUploading]=useState(false); const [error,setError]=useState(''); const fileRef=useRef<HTMLInputElement>(null);
  const selected=draft.cues.find((c)=>c.id===selectedId)||draft.cues[0];
  const patch=(patch:Partial<SoundCue>)=>{if(!selected)return;setDraft((cur)=>({...cur,cues:cur.cues.map((c)=>c.id===selected.id?{...c,...patch}:c),updatedAt:new Date().toISOString()}))};
  const addPreset=(preset:typeof PRESETS[number])=>{const cue:SoundCue={id:makeId(),name:preset.label,source:'synth',preset:preset.id,volume:.7,duration:preset.duration,frequency:preset.frequency,trigger:'click'};setDraft((cur)=>({...cur,cues:[...cur.cues,cue]}));setSelectedId(cue.id)};
  const play=(cue:SoundCue)=>{if(cue.source==='synth')playSynth(cue,draft.masterVolume);else if(cue.url){const a=new Audio(cue.url);a.volume=Math.max(0,Math.min(1,cue.volume*draft.masterVolume));void a.play().catch(()=>setError('O navegador bloqueou a reprodução deste áudio.'))}};
  const upload=async(file:File)=>{if(!file.type.startsWith('audio/')){setError('Escolha um arquivo de áudio.');return}if(file.size>4*1024*1024){setError('Use um efeito de áudio de até 4 MB.');return}setUploading(true);setError('');try{const session=await ensureTursoSession();const r=await fetch('/api/upload',{method:'POST',headers:{'Content-Type':file.type,'X-File-Name':encodeURIComponent(file.name),...(session?.token?{Authorization:`Bearer ${session.token}`}:{})},body:file});const data=await r.json().catch(()=>({}));if(!r.ok||!data.url)throw new Error(data.error||'Falha no upload.');const cue:SoundCue={id:makeId(),name:file.name.replace(/\.[^.]+$/,''),source:'upload',url:data.url,volume:.8,duration:1,frequency:440,trigger:'click'};setDraft((cur)=>({...cur,cues:[...cur.cues,cue]}));setSelectedId(cue.id)}catch(e:any){setError(e?.message||'Falha no upload.')}finally{setUploading(false);if(fileRef.current)fileRef.current.value=''}};
  return <div className="fixed inset-0 z-[126] bg-[#EEEDE9] flex flex-col canvas-control" onPointerDown={(e)=>e.stopPropagation()}>
    <header className="shrink-0 min-h-16 bg-white border-b border-black/10 px-3 sm:px-5 flex items-center gap-3"><button onClick={onClose} className="h-11 w-11 rounded-xl hover:bg-black/5 flex items-center justify-center"><X size={19}/></button><div className="min-w-0 flex-1"><div className="font-bold">{title}</div><div className="text-[10px] font-mono text-neutral-500 uppercase">microsons · feedback · transições · acessibilidade sonora</div></div><StudioAreaGuide area="sound"/><button disabled={!canEdit} onClick={()=>onSave({...draft,updatedAt:new Date().toISOString()})} className="h-11 px-4 rounded-xl bg-black text-white flex items-center gap-2 text-xs font-bold"><Save size={15}/> SALVAR</button></header>
    <ResizableStudioGrid storageKey="SoundStudio:panels" defaults={[28,72]}>
      <aside className="min-h-0 overflow-y-auto bg-white border-b lg:border-b-0 lg:border-r border-black/10 p-4"><div className="text-[9px] font-mono font-bold uppercase tracking-widest text-neutral-500">Efeitos rápidos</div><div className="mt-2 grid grid-cols-2 gap-2">{PRESETS.map((p)=><button key={p.id} onClick={()=>addPreset(p)} className="rounded-xl border border-black/10 p-3 text-left hover:border-black"><div className="text-xs font-bold">{p.label}</div><div className="text-[9px] text-neutral-500 mt-1">{p.hint}</div></button>)}</div><input ref={fileRef} type="file" accept="audio/*" className="hidden" onChange={(e)=>{const f=e.target.files?.[0];if(f)void upload(f)}}/><button onClick={()=>fileRef.current?.click()} disabled={uploading} className="mt-3 w-full h-11 rounded-xl border border-black flex items-center justify-center gap-2 text-[10px] font-mono font-bold">{uploading?<Loader2 size={14} className="animate-spin"/>:<Upload size={14}/>} UPAR EFEITO</button><div className="mt-5 text-[9px] font-mono font-bold uppercase text-neutral-500">Biblioteca do projeto</div><div className="mt-2 space-y-2">{draft.cues.map((cue)=><button key={cue.id} onClick={()=>setSelectedId(cue.id)} className={`w-full rounded-xl border p-3 text-left ${selected?.id===cue.id?'border-black bg-[#F3F2EE]':'border-black/10'}`}><div className="flex items-center justify-between"><span className="text-xs font-bold truncate">{cue.name}</span><span className="text-[8px] font-mono uppercase text-neutral-400">{cue.source}</span></div><div className="text-[9px] text-neutral-500 mt-1">gatilho: {cue.trigger||'manual'}</div></button>)}</div></aside>
      <section className="min-h-0 overflow-y-auto p-4 sm:p-7"><div className="max-w-3xl mx-auto space-y-4">{selected&&<><div className="rounded-2xl border-2 border-black bg-white p-5"><div className="flex items-center justify-between gap-3"><div className="font-bold flex items-center gap-2"><Headphones size={18}/>{selected.name}</div><button onClick={()=>play(selected)} className="h-11 px-4 rounded-xl bg-black text-white flex items-center gap-2 text-xs font-bold"><Play size={15}/> OUVIR</button></div><div className="mt-4 grid sm:grid-cols-2 gap-3"><label className="text-[9px] font-mono text-neutral-500">NOME<input value={selected.name} onChange={(e)=>patch({name:e.target.value})} className="mt-1 h-11 w-full rounded-xl border border-black/10 px-3 text-sm"/></label><label className="text-[9px] font-mono text-neutral-500">GATILHO<input value={selected.trigger||''} onChange={(e)=>patch({trigger:e.target.value})} placeholder="click, hover, sucesso…" className="mt-1 h-11 w-full rounded-xl border border-black/10 px-3 text-sm"/></label><label className="text-[9px] font-mono text-neutral-500">VOLUME · {Math.round(selected.volume*100)}%<input type="range" min={0} max={1} step={.05} value={selected.volume} onChange={(e)=>patch({volume:Number(e.target.value)})} className="mt-2 w-full"/></label>{selected.source==='synth'&&<><label className="text-[9px] font-mono text-neutral-500">FREQUÊNCIA · {selected.frequency} Hz<input type="range" min={80} max={1400} step={10} value={selected.frequency} onChange={(e)=>patch({frequency:Number(e.target.value)})} className="mt-2 w-full"/></label><label className="text-[9px] font-mono text-neutral-500">DURAÇÃO · {selected.duration.toFixed(2)}s<input type="range" min={.04} max={1.5} step={.02} value={selected.duration} onChange={(e)=>patch({duration:Number(e.target.value)})} className="mt-2 w-full"/></label></>}</div>{selected.source!=='synth'&&<label className="mt-3 block text-[9px] font-mono text-neutral-500"><Link size={12} className="inline mr-1"/>URL DO ÁUDIO<input value={selected.url||''} onChange={(e)=>patch({url:e.target.value,source:'url'})} className="mt-1 h-11 w-full rounded-xl border border-black/10 px-3 text-xs"/></label>}</div><button disabled={!canEdit} onClick={()=>{const next=draft.cues.filter((c)=>c.id!==selected.id);setDraft({...draft,cues:next});setSelectedId(next[0]?.id||'')}} className="h-10 px-3 rounded-xl border border-red-200 text-red-700 flex items-center gap-2 text-xs"><Trash2 size={14}/> Remover efeito</button></>}
        <div className="rounded-2xl border border-black/10 bg-white p-4"><div className="font-bold text-sm">Volume geral · {Math.round(draft.masterVolume*100)}%</div><input type="range" min={0} max={1} step={.05} value={draft.masterVolume} onChange={(e)=>setDraft({...draft,masterVolume:Number(e.target.value)})} className="mt-3 w-full"/><p className="mt-2 text-[10px] leading-relaxed text-neutral-500">Som deve complementar, nunca ser a única forma de comunicar estado. Preserve alternativas visuais/textuais para pessoas que não ouvem ou mantêm o dispositivo sem áudio.</p></div>{error&&<div className="rounded-xl border border-red-200 bg-red-50 p-3 text-xs text-red-700">{error}</div>}</div></section>
    </ResizableStudioGrid>
  </div>;
}
