import React, { useState } from 'react';
import { Info, X } from 'lucide-react';

type Area = 'drawing'|'interactive'|'wireframe'|'design-system'|'video'|'ux-writing'|'sound'|'hardware'|'characters'|'game-design'|'apis';

const GUIDES: Record<Area,{title:string;intro:string;bullets:string[];references?:string}> = {
  drawing:{title:'Desenho e imagem',intro:'Use esta área para pensar visualmente antes de fechar a solução. O desenho pode ser rascunho, diagrama, composição, anotação ou matéria-prima para outras ferramentas.',bullets:['Trabalhe por camadas e preserve versões intermediárias.','Use formas, imagem e texto como elementos de composição, não apenas como acabamento.','Quando o desenho virar interface, envie para Wireframe ou Interação e continue editando.'],references:'Sketching User Experiences · Bill Buxton; desenho como ferramenta de projeto.'},
  interactive:{title:'Interação e comportamento',intro:'Aqui você transforma elementos estáticos em comportamento: estados, gatilhos, transições, física, movimento e resposta ao usuário.',bullets:['Defina primeiro o que dispara a ação e qual feedback confirma a mudança.','Teste timing, easing e continuidade sem depender de código final.','Prefira movimentos que comuniquem hierarquia, causalidade e estado.'],references:'The Design of Everyday Things · Don Norman; Material Motion; princípios de animação aplicados à interface.'},
  wireframe:{title:'Wireframes',intro:'Wireframes organizam estrutura, hierarquia e fluxo antes do refinamento visual. O objetivo é testar relações entre conteúdo, navegação e ação.',bullets:['Comece pela tarefa principal e pelos estados necessários.','Use grid, auto layout, componentes e margens para criar consistência.','Valide navegação e responsividade antes de investir no visual final.'],references:'Information Architecture · Rosenfeld, Morville & Arango; Lean UX; padrões de UI responsiva.'},
  'design-system':{title:'Design System',intro:'Um design system transforma decisões visuais e de interface em regras reutilizáveis. Ele conecta marca, tipografia, cor, componentes, espaçamento e acessibilidade.',bullets:['Defina tokens antes de multiplicar componentes.','Teste contraste, estados, escalas tipográficas e comportamento responsivo.','Sincronize com Identidade Visual quando marca e produto compartilham o mesmo sistema.'],references:'Atomic Design · Brad Frost; Design Systems · Alla Kholmatova; WCAG.'},
  video:{title:'Vídeo e movimento',intro:'Use vídeo para construir ritmo, narrativa, demonstração e atmosfera. A edição deve articular imagem, som, tipografia e tempo.',bullets:['Organize primeiro cenas e intenção de cada trecho.','Use transições apenas quando elas ajudam a leitura ou a passagem temporal.','Combine imagens do projeto, texto, voz, trilha e animações em camadas independentes.'],references:'The Animator’s Survival Kit · Richard Williams; princípios de montagem e motion design.'},
  'ux-writing':{title:'UX Writing',intro:'UX Writing projeta a linguagem da interface. O texto deve orientar ação, reduzir ambiguidade e sustentar o tom do projeto.',bullets:['Escreva a partir da tarefa e do contexto, não do espaço disponível.','Considere erros, estados vazios, confirmações e acessibilidade.','Teste versões curtas, claras e coerentes com a voz do projeto.'],references:'Strategic Writing for UX · Torrey Podmajersky; Writing Is Designing · Metts & Welfle.'},
  sound:{title:'Sonoridade',intro:'Som também é interface. Microsons, voz e paisagem sonora podem confirmar ações, criar presença e ampliar acessibilidade.',bullets:['Associe som a eventos claros e evite excesso de estímulos.','Preveja silêncio, volume e alternativa visual para toda informação sonora importante.','Use ritmo, duração e frequência como parte do sistema de feedback.'],references:'Sonic Interaction Design; princípios de earcons, feedback multimodal e acessibilidade.'},
  hardware:{title:'Hardware e sensores',intro:'Esta área conecta o projeto digital ao mundo físico por sensores, microcontroladores e entradas corporais ou ambientais.',bullets:['Comece pelo comportamento desejado antes de escolher o sensor.','Prototipe com poucos sinais e faça calibração visível.','Documente entrada, processamento, saída e condição de erro.'],references:'Physical Computing · Dan O’Sullivan & Tom Igoe; Arduino; Web Serial.'},
  characters:{title:'Personagens e sprites',intro:'Personagem é um sistema visual e comportamental. Construa silhueta, anatomia, expressão, diversidade, acessibilidade, pose e movimento de forma coerente com o projeto.',bullets:['Escolha o tipo de ser antes de definir movimentos e articulações.','Use referências diversas sem transformar identidades em estereótipos.','Turnaround, expression sheet e ciclos de movimento ajudam a manter consistência.'],references:'Creating Characters with Personality · Tom Bancroft; The Silver Way · Stephen Silver; Animator’s Survival Kit.'},
  'game-design':{title:'Game Design',intro:'Game design organiza objetivo, regra, ação, feedback, progressão e experiência da pessoa jogadora. O GDD deve ser testável, não apenas descritivo.',bullets:['Escreva a ação central e o ciclo de feedback antes de detalhar fases.','Puxe personagens, objetos e cenas existentes do projeto para o roteiro.','Use playtest de fluxo para descobrir problemas antes da implementação.'],references:'The Art of Game Design · Jesse Schell; Rules of Play · Salen & Zimmerman; Game Feel · Steve Swink.'},
  apis:{title:'APIs e conexões',intro:'APIs ampliam o repertório do projeto com dados, serviços e capacidades externas. Aqui a prioridade é entender o que cada conexão oferece e como incorporá-la com segurança.',bullets:['Prefira APIs abertas, gratuitas ou com free tier sustentável.','Documente autenticação, limites, origem dos dados e fallback.','Teste visualmente a integração antes de torná-la dependência central do projeto.'],references:'REST/HTTP, documentação do provedor e princípios de progressive enhancement.'},
};

export default function StudioAreaGuide({area}:{area:Area}){
  const [open,setOpen]=useState(false); const guide=GUIDES[area];
  return <><button type="button" onClick={()=>setOpen(true)} className="h-11 w-11 shrink-0 rounded-xl border bg-white flex items-center justify-center" title={`Sobre ${guide.title}`} aria-label={`Sobre ${guide.title}`}><Info size={18}/></button>{open&&<div className="fixed inset-0 z-[190] bg-black/55 p-3 sm:p-8 grid place-items-center" onClick={()=>setOpen(false)}><div className="w-full max-w-3xl max-h-[88vh] overflow-y-auto rounded-3xl bg-white p-6 sm:p-8" onClick={event=>event.stopPropagation()}><div className="flex items-start gap-4"><div className="flex-1"><div className="text-[11px] font-mono uppercase tracking-wide text-neutral-500">SOBRE A ÁREA · GUIA RÁPIDO</div><h2 className="mt-1 text-2xl sm:text-3xl font-bold leading-tight">{guide.title}</h2><p className="mt-4 text-[15px] sm:text-base leading-relaxed text-neutral-700">{guide.intro}</p></div><button onClick={()=>setOpen(false)} className="h-10 w-10 rounded-xl border flex items-center justify-center" aria-label="Fechar"><X size={18}/></button></div><div className="mt-6 rounded-2xl bg-[#111] p-5 text-white"><b className="text-base">Pontos essenciais</b><ul className="mt-3 space-y-3 text-[14px] sm:text-[15px] leading-relaxed text-white/80">{guide.bullets.map(item=><li key={item}>• {item}</li>)}</ul></div>{guide.references&&<div className="mt-4 rounded-2xl border p-4"><div className="text-[11px] font-mono uppercase text-neutral-500">Referências para aprofundar</div><p className="mt-2 text-[14px] leading-relaxed text-neutral-700">{guide.references}</p></div>}</div></div>}</>;
}
